// IELTS 弱点改善ノート — 単一ソースデータ（アプリ・PDF・ノート共通）
// 公式添削（自然な表現＋番号解説）をもとに再構築
window.IELTS_DATA = {
  updated: "2026-07-04",
  goal: "IELTS Band 6.5",

  // ── ミスカード（品詞 / 前置詞 / 冠詞 / コロケーション / 文構造）──
  mistakes: [
    // T1: 手紙 — 病気の友人へ
    { id:"1", cat:"品詞", topic:"手紙: 病気の友人へ", ctx:"体調を崩した友人を気づかう場面。「あなたのことが心配です」。",
      wrong:"I am worry about you", right:"I am worried about you",
      why:"worry は動詞（心配する）。「心配している」という“状態”は形容詞 worried。be動詞 + worried + about。",
      ex:"I am worried about your health. I hope you get well soon." },
    { id:"2", cat:"前置詞", topic:"手紙: 病気の友人へ", ctx:"本題の切り出し。「3点お知らせします」と伝える場面。",
      wrong:"I would like to inform you three items", right:"I would like to inform you of three items",
      why:"inform は inform + 人 + of / about + 物。目的語を2つ並べられず、of（または about）が必要。",
      ex:"I would like to inform you of three points." },
    { id:"3", cat:"前置詞", topic:"手紙: 病気の友人へ", ctx:"手紙の最後。「また学校に戻ってきてね」と励ます場面。",
      wrong:"come back a school again", right:"come back to school again",
      why:"「〜へ戻る」は come back to + 場所。school は go / come back to school で無冠詞（a を付けない）。",
      ex:"I hope you will come back to school soon." },
    { id:"4", cat:"冠詞", topic:"手紙: 病気の友人へ", ctx:"検証結果を「次のミーティングで共有する」と述べる場面。",
      wrong:"share that consequence in next meeting", right:"share the results in the next meeting",
      why:"特定の次回会合なので the next meeting。結果も自分たちのその結果なので the results。可算名詞には冠詞が必要。",
      ex:"We will share the results in the next meeting." },
    { id:"5", cat:"コロケーション", topic:"手紙: 病気の友人へ", ctx:"検証で得た“成果”を共有すると伝える場面。",
      wrong:"share that consequence", right:"share the results / our findings",
      why:"consequence は「（悪い）結果・報い」の意味。研究や実験の「結果・成果」は result(s) / findings を使う。",
      ex:"We are going to share our findings next time." },
    { id:"6", cat:"コロケーション", topic:"手紙: 病気の友人へ", ctx:"課題を挙げ終えて「これが私たちの課題です」とまとめる場面。",
      wrong:"This is our assignments", right:"These are our assignments",
      why:"assignments（複数）が主語 → These are。指示語・be動詞・名詞の“単複”をそろえる（最重要弱点）。※模範では冗長として削除も可。",
      ex:"These are the tasks we must finish before next week." },

    // T2: Task2 — グローバル化
    { id:"7", cat:"品詞", topic:"Task2: グローバル化", ctx:"グローバル化の利点。「簡単に意思疎通できる」と言いたい場面。",
      wrong:"you can do communication easily", right:"you can communicate easily",
      why:"communication（名詞）を do で動詞化しない。「意思疎通する」は動詞 communicate 一語で表す。",
      ex:"Globalisation allows us to communicate easily across borders." },
    { id:"8", cat:"品詞", topic:"Task2: グローバル化", ctx:"同じく利点。「作業を速くこなせる」と続けたい場面。",
      wrong:"you can do task faster", right:"you can complete tasks more quickly",
      why:"動詞は complete / carry out。task は可算名詞で複数 tasks。副詞は faster より more quickly が自然。",
      ex:"We can complete tasks more quickly thanks to technology." },
    { id:"9", cat:"前置詞", topic:"Task2: グローバル化", ctx:"「お互いに意思疎通できる」と言う場面。",
      wrong:"we can communicate each other", right:"we can communicate with each other",
      why:"communicate は自動詞。相手を示すには with が必要。",
      ex:"People from different countries can communicate with each other instantly." },
    { id:"10", cat:"コロケーション", topic:"Task2: グローバル化", ctx:"「グローバルな考えを持つ人と関われば」と述べる場面。",
      wrong:"people who have the global style", right:"people who have a global mindset",
      why:"the global style は曖昧。「国際的な考え方を持つ人」は a global mindset が自然。",
      ex:"People with a global mindset adapt quickly to new cultures." },
    { id:"11", cat:"前置詞", topic:"Task2: グローバル化", ctx:"地方文化が「消滅の危機にある」と言う場面。",
      wrong:"may be in risk of", right:"may be at risk of",
      why:"「〜の危機にある」は固定表現 at risk (of)。in risk とは言わない。",
      ex:"Local traditions are at risk of being lost." },
    { id:"12", cat:"品詞", topic:"Task2: グローバル化", ctx:"地方文化・言語が「消滅」しかねないと述べる場面。",
      wrong:"at risk of dissapperment", right:"at risk of disappearance / disappearing",
      why:"名詞は disappearance、動名詞は disappearing。dissapperment という語は存在しない。",
      ex:"Many languages are at risk of disappearance." },
    { id:"13", cat:"前置詞", topic:"Task2: グローバル化", ctx:"具体例の導入。「こうした欠点を聞いたことがある」場面。",
      wrong:"I have heard of that bad points", right:"I have heard about these drawbacks",
      why:"この文構造では heard about が自然。heard of は「〜の存在を知っている」の意味で用途が違う。",
      ex:"I have heard about these drawbacks from friends abroad." },
    { id:"14", cat:"前置詞", topic:"Task2: グローバル化", ctx:"「アフリカに住む人から聞いた」と例示する場面。",
      wrong:"people who lives Africa", right:"people who live in Africa",
      why:"「〜に住む」は live in + 地名。people は複数なので動詞は live。",
      ex:"People who live in Africa shared their experiences online." },
    { id:"15", cat:"コロケーション", topic:"Task2: グローバル化", ctx:"統計を根拠に「言語数が年々減っている」と述べる場面。",
      wrong:"the number of languages are decreasing as time goes by", right:"the number of languages is decreasing over time",
      why:"主語の中心は the number（単数）→ is。「時間とともに」は over time が自然。",
      ex:"The number of endangered languages is decreasing over time." },
    { id:"16", cat:"コロケーション", topic:"Task2: グローバル化", ctx:"「これもグローバル化の問題の一つだ」とまとめる場面。",
      wrong:"one of the problem", right:"one of the problems",
      why:"one of the + 複数名詞。「〜のうちの1つ」は必ず複数形。",
      ex:"This is one of the problems caused by globalisation." },
    { id:"17", cat:"前置詞", topic:"Task2: グローバル化", ctx:"問題の原因をグローバル化に帰す場面。",
      wrong:"attributed from globalisation", right:"attributed to globalisation",
      why:"「〜に起因する」は attribute A to B。from は不可。",
      ex:"Rising inequality is often attributed to globalisation." },
    { id:"18", cat:"品詞", topic:"Task2: 結論の書き出し", ctx:"最終段落。「まとめると」と結論を書き始める場面。",
      wrong:"In summarization", right:"In summary / To summarise",
      why:"まとめの合図は In summary / To conclude。summarization（要約という行為）は使わない。",
      ex:"In summary, globalisation has both benefits and drawbacks." },
    { id:"19", cat:"冠詞", topic:"Task2: グローバル化", ctx:"「グローバル化を進めれば」と一般論で語り出す場面。",
      wrong:"if we have the globalisation", right:"if we promote globalisation",
      why:"globalisation は抽象・一般概念なので無冠詞。動詞も have より promote が自然。",
      ex:"If we promote globalisation, ideas spread faster." },
    { id:"20", cat:"コロケーション", topic:"Task2: グローバル化", ctx:"「グローバル化をさらに進めれば」と述べる場面。",
      wrong:"if we accelerate more globalization", right:"if we further accelerate globalisation",
      why:"「さらに加速する」は further accelerate。accelerate more は不自然。",
      ex:"If we further accelerate globalisation, cooperation will grow." },
    { id:"21", cat:"前置詞", topic:"Task2: グローバル化", ctx:"「他者と交流する機会が増える」と述べる場面。",
      wrong:"the opportunities of interaction of other people", right:"opportunities for interaction with other people",
      why:"opportunities for（〜の機会）、interaction with（〜との交流）。どちらも決まった前置詞。",
      ex:"Globalisation increases opportunities for interaction with people worldwide." },
    { id:"22", cat:"コロケーション", topic:"Task2: グローバル化", ctx:"交流機会が「増えるだろう」と予測する場面。",
      wrong:"is going to be increasing", right:"will increase",
      why:"未来の増加は will increase で十分。is going to be increasing は冗長・不自然。",
      ex:"Opportunities for interaction will increase due to globalisation." },
    { id:"23", cat:"冠詞", topic:"Task2: グローバル化", ctx:"自分の考えを「一番良い案だ」と述べる場面。",
      wrong:"That is a best idea", right:"That is the best idea",
      why:"最上級には the を付ける（the best / the largest）。",
      ex:"That is the best idea I have come up with." },
    { id:"24", cat:"コロケーション", topic:"Task2: グローバル化", ctx:"逆の立場で「進めるべきでない」と主張する場面。",
      wrong:"we better do not declare and accelerate", right:"we should not continue to promote and accelerate",
      why:"助言は should / had better。we better do not は語順が壊れている。",
      ex:"We should not accelerate globalisation without protecting local cultures." },
    { id:"25", cat:"コロケーション", topic:"Task2: グローバル化", ctx:"「共通言語で世界と対話すべき」と提案する結びの場面。",
      wrong:"we better do conversation ... speaking common language", right:"we should communicate ... by speaking a common language",
      why:"do conversation は不自然。communicate / have conversations を使う。a common language と冠詞も必要。",
      ex:"We should communicate with the world by speaking a common language, such as English." },

    // T3: 会話返信 — 多文化都市の成功例（米国）
    { id:"26", cat:"冠詞", topic:"会話: 多文化の成功例(米国)", ctx:"回答の書き出しで国名を挙げる場面。",
      wrong:"It would be United States of America", right:"It would be the United States of America",
      why:"複数形を含む国名には the（the United States, the Netherlands, the Philippines）。",
      ex:"The United States has long been a nation of immigrants." },
    { id:"27", cat:"コロケーション", topic:"会話: 多文化の成功例(米国)", ctx:"アメリカの多文化での成功を説明する場面。",
      wrong:"successful at multicultural in academia", right:"successful at embracing multiculturalism in academia",
      why:"multicultural は形容詞。名詞は multiculturalism。「多文化を受け入れる」は embrace multiculturalism。",
      ex:"The country is successful at embracing multiculturalism." },
    { id:"28", cat:"前置詞", topic:"会話: 多文化の成功例(米国)", ctx:"「移民に適応して発展してきた」と述べる場面。",
      wrong:"developed by adapting immigration", right:"has developed by adapting to immigration",
      why:"adapt to（〜に適応する）。to が必要。過去から現在まで続くので現在完了 has developed。",
      ex:"The nation has developed by adapting to immigration." },
    { id:"29", cat:"冠詞", topic:"会話: 多文化の成功例(米国)", ctx:"「最近の米国の状況はよく分からない」と述べる場面。",
      wrong:"Recent situation in U.S is unknown", right:"The recent situation in the U.S. is unclear to me",
      why:"特定の状況なので the。国名は the U.S.。unknown より unclear to me が自然。",
      ex:"The recent situation in the U.S. is unclear to me." },
    { id:"30", cat:"文構造", topic:"会話: 多文化の成功例(米国)", ctx:"「トランプ大統領が何を考えているか分からない」と述べる場面。",
      wrong:"I do not know Presdient Trump thinks", right:"I do not know what President Trump thinks",
      why:"know の後に節を続けるには what が必要（know + what + 主語 + 動詞）。",
      ex:"I do not know what the government thinks about this issue." },
    { id:"31", cat:"冠詞", topic:"会話: 多文化の成功例(米国)", ctx:"多文化の具体例（イーロン・マスク）を挙げる場面。",
      wrong:"who is born in diffrerent country", right:"who was born in a different country",
      why:"可算名詞 country に a。「生まれた」は過去の受動 was born。",
      ex:"Elon Musk was born in a different country, South Africa." },
    { id:"32", cat:"コロケーション", topic:"会話: 多文化の成功例(米国)", ctx:"成功例を挙げる導入の場面。",
      wrong:"the example of person who is succeful", right:"one example of a successful person",
      why:"「一例」は one example of a + 名詞。person に a が必要。",
      ex:"One example of a successful immigrant is Elon Musk." },

    // T4: 面接 — 日本で人気の祭り
    { id:"33", cat:"コロケーション", topic:"面接: 日本の人気の祭り", ctx:"「日本で一番人気の祭りは花火（大会）だ」と切り出す場面。",
      wrong:"The most popular festival in Japan is fireworks", right:"The most popular festival events in Japan are fireworks displays",
      why:"花火（fireworks）は物であり祭りそのものではない。festival events / fireworks displays と表し、複数なので are。",
      ex:"Some of the most popular summer events in Japan are fireworks displays." },
    { id:"34", cat:"コロケーション", topic:"面接: 日本の人気の祭り", ctx:"「花火が各地で開催される」と説明する場面。",
      wrong:"The fireworks is held at all locations", right:"The fireworks are held at various locations",
      why:"fireworks は複数扱い → are。all locations（全域）は大げさで、various locations（各地）が自然。",
      ex:"Fireworks are held at various locations across Japan." },
    { id:"35", cat:"文構造", topic:"面接: 日本の人気の祭り", ctx:"「田舎でも開催される」と補足する場面。",
      wrong:"even if there are rual area", right:"even in rural areas",
      why:"スペルは rural。even if there are は文構造が崩れる。even in rural areas で場所を自然につなぐ。",
      ex:"Fireworks are held everywhere, even in rural areas." },
    { id:"36", cat:"コロケーション", topic:"面接: 日本の人気の祭り", ctx:"「屋台が出ている」と描写する場面。",
      wrong:"There are usually food stall on the site", right:"There are usually food stalls on the street",
      why:"屋台は複数 stalls。会場の通りは on the street（on the site は工事現場的で不自然）。",
      ex:"There are usually food stalls lining the street." },
    { id:"37", cat:"コロケーション", topic:"面接: 日本の人気の祭り", ctx:"「食べながら花火を見られる」と述べる場面。",
      wrong:"We can see fireworks eating some delicious foods", right:"We can watch the fireworks while eating delicious food",
      why:"予定された催しは watch。while がないと「花火が食べている」意味に。food は一般に不可算。",
      ex:"We can watch the fireworks while eating delicious food." },

    // T5: Task1 — Facebook円グラフ
    { id:"38", cat:"コロケーション", topic:"Task1: Facebook円グラフ", ctx:"円グラフを描写し始める場面。",
      wrong:"The left circle graph", right:"The left pie chart",
      why:"円グラフは pie chart（circle graph ではない）。IELTS Task1 の必須用語。",
      ex:"The two pie charts compare the ages of Facebook users." },
    { id:"39", cat:"コロケーション", topic:"Task1: Facebook円グラフ", ctx:"各年齢層の割合を述べる場面。",
      wrong:"which dominates 51% users", right:"made up 51% of users / accounted for 51%",
      why:"割合は make up / account for。dominate は「圧倒的多数を占める」ときだけ。",
      ex:"Users aged 13 to 24 made up 51% of the total." },
    { id:"40", cat:"コロケーション", topic:"Task1: Facebook円グラフ", ctx:"概要のあと、細部の数値に入る場面。",
      wrong:"More details, left graph is 51%", right:"In more detail, the left chart shows 51%",
      why:"「詳しく見ると」は In more detail / Looking more closely。",
      ex:"In more detail, the youngest group made up just over half." },
    { id:"41", cat:"文構造", topic:"Task1: Facebook円グラフ", ctx:"「66〜80歳の利用が最も少ない」と述べる場面。",
      wrong:"aged for 66 to 80 people use less this Facebook", right:"people aged 66 to 80 used Facebook the least",
      why:"年齢は people aged 66 to 80（for は不要）。過去データなので used。語順は people aged ... used Facebook。",
      ex:"People aged 66 to 80 used Facebook the least." },

    // T6: 手紙 — 塾への応募
    { id:"42", cat:"文構造", topic:"手紙: 塾への応募", ctx:"自己紹介＋志望動機の書き出し。",
      wrong:"I am Kaito from Japan who am intersted", right:"I am Kaito from Japan, and I am interested",
      why:"who am は不可。自分のことは I を主語に and I am interested と続ける。",
      ex:"My name is Kaito, and I am interested in your school." },
    { id:"43", cat:"前置詞", topic:"手紙: 塾への応募", ctx:"「広告を見て興味を持った」と伝える場面。",
      wrong:"I am curious your cram school seeing its advertisement", right:"I became curious about your cram school after seeing its advertisement",
      why:"curious about（〜に興味）。「広告を見て“から”」は after seeing。become で「興味を持ち始めた」。",
      ex:"I became curious about your school after seeing the advertisement." },
    { id:"44", cat:"品詞", topic:"手紙: 塾への応募", ctx:"経歴として「大学院を卒業した」と述べる場面。",
      wrong:"I have graduated from graduated school", right:"I graduated from graduate school",
      why:"「大学院」は graduate school。過去の一度きりの事実は過去形 graduated（現在完了は不要）。",
      ex:"I graduated from graduate school, where I studied IT." },
    { id:"45", cat:"前置詞", topic:"手紙: 塾への応募", ctx:"「ITを学んだ」と専攻を述べる場面。",
      wrong:"studying about IT", right:"studying IT",
      why:"study は他動詞で目的語を直接とる。about は不要。",
      ex:"I studied IT at graduate school." },
    { id:"46", cat:"冠詞", topic:"手紙: 塾への応募", ctx:"「プログラミングを教えられる」とアピールする場面。",
      wrong:"I can teach the programming", right:"I can teach programming",
      why:"programming は不可算の活動名。一般論として語るときは無冠詞。",
      ex:"I can teach programming to beginners." },
    { id:"47", cat:"冠詞", topic:"手紙: 塾への応募", ctx:"「モバイルアプリを開発している」と述べる場面。",
      wrong:"developing moble application", right:"developing mobile applications",
      why:"スペルは mobile。一般的な「モバイルアプリ」は複数形 applications にする。",
      ex:"I have recently been developing mobile applications." },
    { id:"48", cat:"文構造", topic:"手紙: 塾への応募", ctx:"「ITを教えるのに適任」とアピールする場面。",
      wrong:"I can suitable for teaching", right:"I am suitable / well qualified for teaching",
      why:"suitable は形容詞なので be動詞が必要（can は不可）。I am suitable for + 名詞。",
      ex:"I am well suited to teaching IT to children." },

    // ── Task2: 菜食主義（ベジタリアン）──
    { id:"49", cat:"品詞", topic:"Task2: 菜食主義", ctx:"「その観点からある程度は同意できる」と述べる場面。",
      wrong:"I could some agree to this thought", right:"I can somewhat agree with this opinion",
      why:"some（限定詞）では「いくらか同意」を表せない。程度を表すのは副詞 somewhat。同意は agree with + 意見。",
      ex:"I can somewhat agree with this opinion." },
    { id:"50", cat:"前置詞", topic:"Task2: 菜食主義", ctx:"「宗教の観点からこの問題を説明する」と切り出す場面。",
      wrong:"I describe about this issue", right:"I will describe this issue",
      why:"describe は他動詞で目的語を直接とる。about は不要（discuss / study も同様）。",
      ex:"Let me describe this issue from a religious standpoint." },
    { id:"51", cat:"前置詞", topic:"Task2: 菜食主義", ctx:"「自分の意見の理由を述べる」と予告する場面。",
      wrong:"I am going to state this reason for my idea", right:"I will state the reasons for my opinion",
      why:"「〜の理由」は the reason(s) for。理由が複数なら reasons。idea より opinion が自然。",
      ex:"I will state the reasons for my opinion." },
    { id:"52", cat:"コロケーション", topic:"Task2: 菜食主義", ctx:"「ベジタリアンの考え方」と表現する場面。",
      wrong:"the thinking way of vegetarians", right:"the way of thinking of vegetarians",
      why:"「考え方」は the way of thinking。thinking way とは言わない。",
      ex:"The way of thinking of vegetarians resembles certain religious beliefs." },
    { id:"53", cat:"コロケーション", topic:"Task2: 菜食主義", ctx:"「多くのイスラム教徒は宗教上、豚肉を食べない」と例示する場面。",
      wrong:"Almost of all muslims do not have porks", right:"Almost all Muslims do not consume pork",
      why:"「食べる」は eat / consume（have より consume が自然）。pork は不可算で複数 s を付けない。Muslims は大文字。",
      ex:"Almost all Muslims do not consume pork for religious reasons." },
    { id:"54", cat:"コロケーション", topic:"Task2: 菜食主義", ctx:"「ヒンドゥー教徒は豚肉も牛肉も食べない」と続ける場面。",
      wrong:"hindees do not eat porks and beefs", right:"Hindus do not eat pork or beef",
      why:"pork / beef は不可算（複数 s 不可）。否定文で「A も B も〜ない」は and ではなく or。",
      ex:"Hindus do not eat pork or beef." },
    { id:"55", cat:"コロケーション", topic:"Task2: 菜食主義", ctx:"「気候変動や環境問題が近年議論されている」と述べる場面。",
      wrong:"global warmings and environmental dicernings", right:"climate change and environmental concerns",
      why:"global warming は不可算（warmings 不可）。定番語は climate change / environmental concern(s)。",
      ex:"Climate change and environmental concerns are widely discussed today." },
    { id:"56", cat:"コロケーション", topic:"Task2: 菜食主義", ctx:"「感謝の欠如から来ているのかもしれない」と述べる場面。",
      wrong:"come from lack of appreciation", right:"stem from a lack of appreciation",
      why:"「〜に起因する」は stem from。「〜の不足」は a lack of と a が付く定型。",
      ex:"The problem may stem from a lack of appreciation." },
    { id:"57", cat:"冠詞", topic:"Task2: 菜食主義", ctx:"「食の大切さを見直す良い機会だ」と締める場面。",
      wrong:"is good opportunity to re-think", right:"is a good opportunity to rethink",
      why:"単数・不特定の可算名詞には a/an。a good opportunity。",
      ex:"This is a good opportunity to rethink our eating habits." },
    { id:"58", cat:"文構造", topic:"Task2: 菜食主義", ctx:"「この問題は宗教の観点から捉えられると思う」と述べる場面。",
      wrong:"I believe in this problem is going to be treated", right:"I believe this matter can be viewed through religion",
      why:"意見は believe (that) + 節。believe in は「〜を信頼する」で意味が違い、in を入れると文がねじれる。",
      ex:"I believe this issue can be viewed from several angles." },
    { id:"59", cat:"文構造", topic:"Task2: 菜食主義", ctx:"「ベジタリアンかどうかは個人の選択だ」と述べる場面。",
      wrong:"Whether vegitarians or not is a trivial problem", right:"Whether one chooses to be a vegetarian or not is a personal decision",
      why:"whether 節には主語＋動詞が必要。Whether vegetarians or not では主語・動詞が欠落している。",
      ex:"Whether one becomes a vegetarian or not is a personal choice." },
    { id:"60", cat:"文構造", topic:"Task2: 菜食主義", ctx:"文と文をつなぐ接続詞を選ぶ場面（書き言葉）。",
      wrong:"So, maybe discussion of vegetarianism is good", right:"Therefore, discussing vegetarianism is good",
      why:"書き言葉では文頭に等位接続詞(And/But/So)を置かない。接続副詞(Therefore/However/Similarly)を使う。",
      ex:"Therefore, discussing vegetarianism is a good opportunity to rethink our habits." },
    { id:"61", cat:"文構造", topic:"文法: a number of / the number of", ctx:"「多くの〜」か「〜の数」かで動詞の単複が変わる場面。",
      wrong:"A number of factors has contributed", right:"A number of factors have contributed",
      why:"a number of + 複数名詞 =「多くの〜」で動詞は複数(have/are)。中心は後ろの複数名詞。一方 the number of + 複数名詞 =「〜の数」で中心は number（単数）→動詞は単数(has/is)。a number of は many に置き換えられれば複数動詞。",
      ex:"A number of factors have contributed to this problem." }
  ],

  top5: [
    { rank:1, title:"主語と動詞の一致 / 単数・複数", symptom:"the number ... are / These are / fireworks are / one of the problems / food stalls",
      fix:"名詞を書いたら「1つ？複数？」、動詞を書いたら「主語は単数？」を毎回自問" },
    { rank:2, title:"名詞を無理に動詞化・品詞ミス", symptom:"do communication / do conversation / worry→worried / disappearance / In summary",
      fix:"「〜する」は動詞1語を探す。状態は形容詞（worried）、まとめは In summary" },
    { rank:3, title:"前置詞のセット", symptom:"inform of / at risk / attributed to / adapt to / communicate with / live in / curious about / study∅",
      fix:"動詞・形容詞を前置詞ごと暗記。study は about不要、come back to school" },
    { rank:4, title:"冠詞（a / the / 無冠詞）", symptom:"the U.S. / the best / a common language / teach programming / the microscope",
      fix:"抽象名詞＝無冠詞、可算単数＝a、最上級・特定＝the、複数国名＝the" },
    { rank:5, title:"be動詞・語順・文構造の欠落", symptom:"I can suitable / who am interested / know what he thinks / aged for 66 to 80",
      fix:"英文には動詞が必ず1つ。形容詞の前に be動詞。know の後は what+主語+動詞" }
  ],

  week: [
    { day:"月", theme:"主語・動詞の一致", task:"TOP1の例文を10文書き換え。the number of / a number of・This is/These are の違いを5文ずつ作る" },
    { day:"火", theme:"品詞（動詞化ミス）", task:"do + 名詞 を正しい動詞に直すドリル20問。worry→worried など形容詞化も練習" },
    { day:"水", theme:"前置詞コロケーション", task:"inform of / adapt to / attributed to / communicate with / curious about など20個を暗記→穴埋め自作" },
    { day:"木", theme:"冠詞", task:"自分の英文を印刷し、名詞に○を付けて a / the / 無冠詞を判定するだけの日" },
    { day:"金", theme:"Task2 本番演習", task:"グローバル化の問題を40分で250語。書き終えたら模範（自然な表現）と照合" },
    { day:"土", theme:"Task1 本番演習", task:"グラフ問題を20分で150語。pie chart / made up / accounted for / whereas を必ず使う" },
    { day:"日", theme:"復習＆音読", task:"直した模範文（自然＋改良）を音読5回＋書き写し1回。正しい語順を体に入れる" }
  ],

  priority: [
    { tier:"🥇 最優先", desc:"2週間で+0.5狙える", items:["主語動詞の一致 & 単複（失点が半分近く減る）","be動詞・動詞の欠落をゼロに（文に動詞1つを徹底）"] },
    { tier:"🥈 次点", desc:"語彙の質・自然さで+0.5", items:["前置詞コロケーションの固定化（inform of / adapt to など）","冠詞の判断（抽象名詞は無冠詞、可算単数は a、特定は the）"] },
    { tier:"🥉 6.5→7.0", desc:"余裕が出たら", items:["Task1専用語彙（pie chart / made up / accounted for / whereas）","改良版のような言い換え・複文（which / albeit / turning to）を正確に"] }
  ],

  // ── 模範解答（各設問: 問題文 / あなたの原文 / 自然な表現 / 改良版）──
  essays: [
    { id:"E1", title:"手紙: 病気の友人への研究連絡", words:"150語以上", prompt:"Write an email to a friend. Begin: Dear ......,",
      original:"Dear My friend,\n\nHello, how are you, my firend? I am the leader of a science project. I have heard you are sick. I am worry about you.\n\nI would like to infrom you three items; today's content of group work, plans to do at the next meeting and assignments for the next meeting.\n\nFirst of all, about today's content of group work, we conducted the validation of micro-scope accuracy. You know we have collected some data? We used that data for validation. We are going to share that consequence in next meeting.\n\nSecond, about plans to do at next meeting is going to be a discussion sharing about the collected data we conducted.\n\nLastly, the assignments for the next meeting would be reading and analyzing the collected data. This is our assignments.\n\nI hope you will come back a school again! See you later!\n\nSincrely,",
      natural:"Dear Ryotaro,\n\nI was informed that you are not feeling well, which is why you were unable to attend today's group meeting for our science project. I am sorry to hear that, and I wish you a speedy recovery.\n\nI would like to inform you of three items: today's content of group work, plans for the next meeting, and assignments for the next meeting.\n\nFirst of all, regarding today's content of group work, we conducted the validation of microscope accuracy. You know we have collected some data for validation, and we are going to share the results in the next meeting.\n\nSecond, the plan for the next meeting is going to be a discussion about the data we collected.\n\nLastly, the assignments for the next meeting will be reading and analyzing the collected data.\n\nI hope you will come back to school again! See you later!\n\nSincerely,\nKaito" },

    { id:"E2", title:"Task2: グローバル化の利点と欠点", words:"250語以上", prompt:"Give reasons for your answer and include relevant examples from your own knowledge or experience.",
      original:"There are good points and bad points respectively.\n\nFirst of all, in terms of good points, we can accelerate the speed of transaction which means that you can do communication easily and you can do task faster due to globalisation. If we communicate with other poeple who have the global style, we can easily and faster communicate each other. And also, we can understand each other more deeply than other style.\n\nOn the other hand, there are some bad points. So, if we have the globalisation, culture of local or rural area may be in risk of dissapperment. For example, I have heard of that bad points from people who lives Africa on YouTube. And also I have noticed some statistics show that the number of languages are decreasing as time goes by. So, this is also one of the problem attributed from globalisation.\n\nIn summarization, there are good points and bad points respectively. Maybe, if we accelerate more globalization, but we have the chance to produce some innovative idea discussing with each other which is come from the good aspect of globalization, understanding of diversity. And also, the opportunities of interaction of other people is going to be increasing due to globalisation. That is a best idea I have come up with. Otherwise, we better do not declare and accelerate the globalisation. In order to vitalize the opportunities of globalisation, we better do conversation from all over the world speaking common language, for example, English that leads to world's development.",
      natural:"There are both good points and bad points.\n\nFirst of all, one good point is that we can accelerate the speed of transactions, which means that we can communicate more easily and complete tasks more quickly due to globalisation. If we communicate with other people who have a global mindset, we can communicate with each other more easily and efficiently. In addition, we can understand each other more deeply than we could with people who have different perspectives.\n\nOn the other hand, there are some drawbacks. If we promote globalisation, the cultures of local or rural areas may be at risk of disappearance. I have heard about these drawbacks from people who live in Africa on YouTube. I have also noticed that some statistics show that the number of languages is decreasing over time. So, this is also one of the problems attributed to globalisation.\n\nIn summary, there are both advantages and disadvantages. If we further accelerate globalisation, we will have more opportunities to produce innovative ideas by discussing them with one another. This is one of the positive aspects of globalisation because it promotes an understanding of diversity. In addition, opportunities for interaction with other people will increase due to globalisation.\n\nThat said, we should not promote and accelerate globalisation without care. In order to maximise its benefits, we should communicate with people from all over the world by speaking a common language, such as English, which can contribute to global development." },

    { id:"E3", title:"会話返信: 多文化都市の成功例", words:"短答", prompt:"If you had to choose one real city or country as an example of multicultural success, which one would it be and why?",
      original:"It would be United States of America. Because this country is succesful at multicultural in academia and industry. This country developed by adapting immigration. Recent situation in U.S is unknown and I do not know Presdient Trump thinks. But actually the example of person who is succeful and benefited from multicultural cities features is Eron Musk who is born in diffrerent country, South Africa.",
      natural:"It would be the United States of America, because this country is successful at embracing multiculturalism in academia and industry. This country has developed by adapting to immigration.\n\nThe recent situation in the U.S. is unclear to me, and I do not know what President Trump thinks. But actually, one example of a person who is successful and has benefited from the multicultural nature of American cities is Elon Musk, who was born in a different country, South Africa." },

    { id:"E4", title:"面接: 母国で人気の祭り", words:"短答", prompt:"What is the most popular festival in your home country? Why?",
      original:"The most popular festival in Japan is fireworks. The fireworks is held at all locations even if there are rual area. There are usually food stall on the site. We can see fireworks eating some delicious foods.",
      natural:"The most popular festival events in Japan are fireworks displays. The fireworks are held at various locations, even in rural areas. There are usually food stalls on the street. We can watch the fireworks while eating some delicious food.",
      improved:"Some of the most popular summer festivals in Japan center around spectacular fireworks displays. These events take place all over the country, even in remote rural towns. The festival grounds are usually lined with traditional food stalls, allowing you to snack on local delicacies while taking in the show." },

    { id:"E5", title:"Task1: Facebook利用者の年齢層（円グラフ）", words:"150語以上", prompt:"Summarise the information by selecting and reporting the main features, and make comparisons where relevant.",
      original:"This graph is about the age range of Facebook users in 2005 and 2015. The left circle graph is about 2005 data which dominates 51% users for Facebook users. On the other hand, the right graph dominates 47% in 2015 data. That's a big difference between them. Interestingly, each graph shows that aged for 66 to 80 people use less this Facebook. More details, left graph is 51% for 13 to 24 age, 32% for 25 to 40 age, 16% for 41 to 65 age, and 1% for 66 to 80 age. Right graph is 31% for 13 to 24 age, 47% for 25 to 40 age, 19% for 41 to 65 age, and 3% for 66 to 80.",
      natural:"These pie charts show information on the age range of Facebook users in 2005 and 2015.\n\nThe left pie chart shows 2005 data, which indicates that Facebook users aged 13 to 24 were the dominant group. On the other hand, the right pie chart for 2015 data shows that the majority of Facebook users were aged 25 to 40. Interestingly, each pie chart shows that people aged 66 to 80 used Facebook less than the other three age groups.\n\nIn more detail, for the left pie chart, it can be seen that the 13 to 24 age group made up 51% of all Facebook users, followed by the 25 to 40 age group with 32%. The remaining two age groups, 41 to 65 and 66 to 80, accounted for 16% and 1% of users, respectively.\n\nTurning to the right pie chart, a noticeable change can be observed. The number of users aged 13 to 24 fell to 31%, while that of users aged 25 to 40 rose to 47%. The proportions of users aged 41 to 65 and 66 to 80 also increased, albeit slightly: the 41 to 65 age group rose to 19%, and the 66 to 80 age group climbed to 3%." },

    { id:"E6", title:"手紙: 塾への応募（フォーマル）", words:"150語以上", prompt:"Write a letter. Begin: Dear Sir or Madam,",
      original:"Dear Sir,\n\nI am Kaito from Japan who am intersted in your cram school. I am curious your cram school seeing its advertisement.\n\nI have graduated from graduated school in Japan, studying about IT. So I can teach the programming and IT. And Also, I recently have been developing moble application, so I can suitable for teaching IT to the children who are interested in IT.\n\nSincerely,",
      natural:"Dear Sir,\n\nI am Kaito from Japan, and I am interested in your cram school. I became curious about your cram school after seeing its advertisement.\n\nI graduated from graduate school in Japan, where I studied IT, so I can teach programming and IT. Also, I have recently been developing mobile applications, which means I am well suited to teaching IT to children who are interested in the field.\n\nI look forward to hearing from you.\n\nSincerely,\nKaito" },

    { id:"E7", title:"Task2: 菜食主義（ベジタリアン）", words:"250語以上", prompt:"Some people believe that everyone should adopt a vegetarian diet. To what extent do you agree? Give reasons and examples.",
      original:"It is difficult to answer to that because this problem is sensitive. I believe in this problem is going to be treated as a kind of a religion issue. I could some agree to this thought of vegetarians from that aspect. I am going to state this reason for my idea.\n\nFist of all, I describe about this issue from aspect of religion problem. For example, Almost of all muslims do not have porks because of aspetct of religion issue. And also hindees do not eat porks and beefs. In that sense, the thinking way of vegetarians is simillar to the regilion issues representative for muslims and hindees.\n\nSecondly, this problem could be thought from the perspective of era. I wonder there has been lots of vegetarians since long times ago. Global problem such as global warmings and environmental dicernings have been discussed lately. In that sense, the idea of vegitarians could be thought as a relevant isssue to that global problem. Under affects of the propagation of the internet, this vegetarians problem has been discussing more frequently. Whether vegitarians or not is a trivial problem I think. But when some people see and meet the vegitarians's idea via internet who are not familiar with that idea, discussion between vegetarians and not are vitalised.\n\nLastly, the aspect of eating meets of animals is too highlighted to discuss. We have been appreciated when we eat food in Japan since long times ago. The reasons for attention of vegetalisms maybe come from lack of aprreciation. Today, methods in the field of technology such as delivery tasks and plantation, farming, and live stocks are very mature comparing to the very old era. So, maybe discussion of vegitalisms is good opportunity to re-think the importance of food inculuding both of animals and vegitables in this era.",
      natural:"It is difficult to address this issue because it is sensitive. I believe this matter can be viewed through the lens of religious beliefs. From this perspective, I can somewhat agree with the thoughts of vegetarians. I will state the reasons for my opinion.\n\nFirst of all, I will describe this issue from a religious standpoint. For example, almost all Muslims do not consume pork because of religious beliefs. Similarly, Hindus do not eat pork or beef. In that sense, the way of thinking of vegetarians can be compared to the religious beliefs of Muslims and Hindus.\n\nSecondly, this problem can also be examined from a historical perspective. There have been many vegetarians for a long time. Global problems such as climate change and environmental concerns have been discussed lately. In this context, vegetarianism can be viewed as a relevant response to these global challenges. With the proliferation of the internet, discussions about vegetarianism have become more frequent. Whether one chooses to be a vegetarian or not is a personal decision. Still, when those unfamiliar with the idea encounter vegetarians online, it stimulates important discussions between the two perspectives.\n\nLastly, the topic of eating animal meat deserves attention. In Japan, we have long expressed gratitude for the food we consume. The rising focus on vegetarianism might stem from a lack of appreciation for our food sources. Today, advancements in technology, such as delivery services, agriculture, and livestock management, are more developed than in the past. Therefore, discussing vegetarianism presents a good opportunity to rethink the importance of food, including both animal meat and vegetables, in this era." }
  ]
};
