// IELTS 弱点改善ノート — ミスデータ（印刷用PDF・ウェブアプリ共通）
window.IELTS_DATA = {
  updated: "2026-07-04",
  goal: "IELTS Band 6.5",
  mistakes: [
    // A. 品詞
    { id:"A-1", cat:"品詞", wrong:"you can do communication easily", right:"you can communicate easily",
      why:"communication（名詞）を do で無理に動詞化している。「意思疎通する」は動詞 communicate 一語で表す。",
      ex:"Social media allows people to communicate across borders instantly." },
    { id:"A-2", cat:"品詞", wrong:"you can do task faster", right:"you can complete tasks faster",
      why:"動詞は complete / carry out / perform。task は可算名詞なので a task か複数形 tasks が必要。",
      ex:"Automation helps employees complete tasks more efficiently." },
    { id:"A-3", cat:"品詞", wrong:"at risk of dissapperment", right:"at risk of disappearing / disappearance",
      why:"名詞は disappearance、動名詞は disappearing。dissapperment という単語は存在しない（スペルも誤り）。",
      ex:"Many minority languages are at risk of disappearing within a generation." },
    { id:"A-4", cat:"品詞", wrong:"In summarization", right:"In summary, / To summarise,",
      why:"まとめの定型句は In summary か To conclude。summarization は「要約という行為」を指す技術用語で結論の合図には使わない。",
      ex:"To summarise, the benefits of globalisation outweigh its drawbacks." },
    { id:"A-5", cat:"品詞", wrong:"successful at multicultural in academia", right:"successful in promoting multiculturalism",
      why:"multicultural は形容詞（多文化の）。「多文化主義」という名詞は multiculturalism。",
      ex:"Canada is often praised for its policy of multiculturalism." },
    { id:"A-6", cat:"品詞", wrong:"I have graduated from graduated school", right:"I graduated from graduate school",
      why:"「大学院」は graduate school（graduate は形容詞的に使う）。過去の一度きりの事実は過去形 graduated でよい。",
      ex:"After graduate school, I began working as a software engineer." },

    // B. 前置詞
    { id:"B-1", cat:"前置詞", wrong:"we can communicate each other", right:"we can communicate with each other",
      why:"communicate は自動詞で、相手を示すには with が必要。",
      ex:"Colleagues in different countries can now communicate with each other in real time." },
    { id:"B-2", cat:"前置詞", wrong:"may be in risk of", right:"may be at risk of",
      why:"「〜の危機にある」は固定表現 at risk (of)。in risk とは言わない。",
      ex:"Local traditions are at risk of being lost." },
    { id:"B-3", cat:"前置詞", wrong:"people who lives Africa", right:"people who live in Africa",
      why:"「〜に住む」は live in + 場所。主語 people は複数なので動詞は live。",
      ex:"People who live in rural areas often preserve older customs." },
    { id:"B-4", cat:"前置詞", wrong:"attributed from globalisation", right:"attributed to globalisation",
      why:"「〜に起因する／〜のせいにされる」は attribute A to B。from は不可。",
      ex:"Rising inequality is often attributed to globalisation." },
    { id:"B-5", cat:"前置詞", wrong:"I am curious your cram school", right:"I am curious about your school",
      why:"curious は必ず about を伴う。",
      ex:"I am curious about the teaching methods used at your school." },
    { id:"B-6", cat:"前置詞", wrong:"I can suitable for teaching", right:"I am well suited to teaching",
      why:"suitable for + 名詞、suited to + 名詞/-ing。動詞 am を必ず入れる。",
      ex:"My background makes me well suited to teaching programming." },

    // C. 冠詞
    { id:"C-1", cat:"冠詞", wrong:"It would be United States of America", right:"It would be the United States of America",
      why:"複数形を含む国名には the が付く（the United States, the Netherlands, the Philippines）。",
      ex:"The United States has long been a nation of immigrants." },
    { id:"C-2", cat:"冠詞", wrong:"if we have the globalisation", right:"with globalisation",
      why:"globalisation のような抽象・一般概念には冠詞を付けない。",
      ex:"With globalisation, ideas spread faster than ever before." },
    { id:"C-3", cat:"冠詞", wrong:"speaking common language", right:"speaking a common language",
      why:"language は可算名詞。「1つの共通言語」なので a が必要。",
      ex:"Sharing a common language makes international cooperation easier." },
    { id:"C-4", cat:"冠詞", wrong:"who is born in diffrerent country", right:"who was born in a different country",
      why:"可算名詞 country に a。また「生まれた」は過去の受動 was born。",
      ex:"Elon Musk was born in a different country, South Africa." },
    { id:"C-5", cat:"冠詞", wrong:"I can teach the programming and IT", right:"I can teach programming and IT",
      why:"programming は不可算の学問・活動名。一般論として語るときは無冠詞。",
      ex:"I can teach programming to beginners." },
    { id:"C-6", cat:"冠詞", wrong:"The fireworks is held at all locations", right:"Fireworks displays are held in many areas",
      why:"fireworks は複数扱い → be動詞は are。また「花火大会」は a fireworks display / festival。",
      ex:"Fireworks displays are held across Japan every summer." },

    // D. コロケーション
    { id:"D-1", cat:"コロケーション", wrong:"The most popular festival in Japan is fireworks.", right:"One of the most popular festivals is the fireworks festival.",
      why:"「祭り＝花火」ではなく「花火大会（祭り）」。物（fireworks）とイベント（festival）を混同しない。",
      ex:"One of the most popular summer events in Japan is the fireworks festival." },
    { id:"D-2", cat:"コロケーション", wrong:"The left circle graph dominates 51% users", right:"The left pie chart shows that ... accounted for 51% of users",
      why:"IELTS Task1では pie chart（円グラフ）。割合を述べる動詞は account for / make up / represent。dominate は「圧倒的多数を占める」ときだけ。",
      ex:"Users aged 25–40 accounted for 47% of the total in 2015." },
    { id:"D-3", cat:"コロケーション", wrong:"More details, left graph is 51%", right:"In more detail, the left chart shows 51%",
      why:"「詳しく言うと」は In more detail か Looking more closely。",
      ex:"In more detail, the figure for younger users fell sharply." },
    { id:"D-4", cat:"コロケーション", wrong:"we better do conversation from all over the world", right:"we should have conversations with people from all over the world",
      why:"conversation は have と結びつく（do ではない）。",
      ex:"Students should have conversations with native speakers regularly." },
    { id:"D-5", cat:"コロケーション", wrong:"we better do not declare and accelerate", right:"we should not promote / we had better not accelerate",
      why:"助言は should か had better。we better do not は語順・形が崩れている。IELTSでは自然な should を推奨。",
      ex:"Governments should not ignore the cultural costs of globalisation." },
    { id:"D-6", cat:"コロケーション", wrong:"This country developed by adapting immigration", right:"This country has thrived by embracing immigration",
      why:"adapt（適応する）ではなく embrace / welcome（受け入れる）。移民に対して使う自然な動詞。",
      ex:"The nation has thrived by embracing people from many cultures." },
    { id:"D-7", cat:"コロケーション", wrong:"the number of languages are decreasing", right:"the number of languages is decreasing",
      why:"主語の中心は the number（単数）→ 動詞は is。※ a number of languages are なら複数。この2つは頻出の区別。",
      ex:"The number of endangered languages is rising every decade." },
    { id:"D-8", cat:"コロケーション", wrong:"Dear Sir, ... Sincerely,", right:"Dear Sir/Madam, ... Yours faithfully,",
      why:"相手の名前が不明で Dear Sir/Madam の場合は Yours faithfully。名前がわかる Dear Mr Tanaka なら Yours sincerely。IELTS Formal Letterの定番ルール。",
      ex:"Dear Sir or Madam, … Yours faithfully, Kaito" }
  ],

  top5: [
    { rank:1, title:"主語と動詞の一致 / 単数・複数", symptom:"the number ... are / who lives / one of the problem / food stall",
      fix:"名詞を書いたら「1つ？複数？」、動詞を書いたら「主語は単数？」を毎回自問" },
    { rank:2, title:"名詞を無理に動詞化（品詞）", symptom:"do communication / do task / do conversation",
      fix:"「〜する」は動詞1語を探す（communicate / complete / converse）" },
    { rank:3, title:"前置詞のセット", symptom:"communicate each other / in risk / attributed from / curious your",
      fix:"動詞・形容詞を前置詞ごと暗記（communicate with / at risk / attribute to / curious about）" },
    { rank:4, title:"冠詞（a / the / 無冠詞）", symptom:"the globalisation / United States / teach the programming / common language",
      fix:"抽象名詞＝無冠詞、可算単数＝a、複数国名＝the" },
    { rank:5, title:"be動詞・語順の欠落", symptom:"I can suitable / who am interested / I do not know President thinks",
      fix:"「英文には動詞が必ず1つ」。関係詞の後は what/who + 主語 + 動詞" }
  ],

  week: [
    { day:"月", theme:"主語・動詞の一致", task:"TOP1の例文を10文書き換え。the number of / a number of の違いを5文ずつ作る" },
    { day:"火", theme:"品詞（動詞化ミス）", task:"do + 名詞 を正しい動詞に直すドリル20問。自分の過去作文から10個抜き出す" },
    { day:"水", theme:"前置詞コロケーション", task:"動詞＋前置詞リスト20個を暗記→穴埋め自作（communicate with / attribute to / depend on / result in）" },
    { day:"木", theme:"冠詞", task:"自分の英文を印刷し、名詞に○を付けて a/the/無冠詞を判定するだけの日" },
    { day:"金", theme:"Task2 本番演習", task:"Globalisationの問題を40分で250語。書き終えたらA〜Dで自己チェック" },
    { day:"土", theme:"Task1 本番演習", task:"グラフ問題を20分で150語。account for / make up / whereas / compared with を必ず3回使う" },
    { day:"日", theme:"復習＆音読", task:"直したAfter模範文を音読5回＋書き写し1回。正しい語順を体に入れる" }
  ],

  priority: [
    { tier:"🥇 最優先", desc:"2週間で+0.5狙える", items:["主語動詞の一致 & 単複（失点が半分近く減る）","be動詞・動詞の欠落をゼロに（文に動詞1つを徹底）"] },
    { tier:"🥈 次点", desc:"語彙の質・自然さで+0.5", items:["前置詞コロケーションの固定化（communicate with 等）","冠詞の判断（抽象名詞は無冠詞、可算単数は a）"] },
    { tier:"🥉 6.5→7.0", desc:"余裕が出たら", items:["Task1専用語彙（pie chart / account for / whereas）","複文の多様化（which / although / not only ... but also）を正確に"] }
  ],

  essays: [
    { title:"Essay 1 — Globalisation",
      after:"There are both advantages and disadvantages to globalisation. First, in terms of the benefits, it accelerates the speed of transactions, which means that people can communicate more easily and complete tasks faster. When we communicate with people who share a global mindset, we can understand one another more deeply. On the other hand, there are some drawbacks. With globalisation, the cultures of local and rural areas may be at risk of disappearing. For example, I have heard about this problem from people who live in Africa on YouTube, and some statistics show that the number of languages is decreasing over time. This is one of the problems attributed to globalisation. In summary, globalisation has both merits and demerits. If it continues, it may give us the chance to produce innovative ideas through discussion and a better understanding of diversity, and opportunities for interaction will keep increasing. To make the most of these opportunities, people around the world should communicate in a common language, such as English, which contributes to global development." },
    { title:"Essay 2 — Most successful multicultural country",
      after:"It would be the United States of America, because this country has been successful in promoting multiculturalism in both academia and industry. It has developed by embracing immigration. The recent situation in the U.S. is uncertain, and I do not know what President Trump thinks. However, one clear example of a person who has benefited from a multicultural environment is Elon Musk, who was born in a different country, South Africa." },
    { title:"Essay 3 — Japanese festival",
      after:"One of the most popular festivals in Japan is the fireworks festival. Fireworks displays are held in many areas, even in the countryside. There are usually food stalls at the venue, so we can enjoy the fireworks while eating delicious food." },
    { title:"Essay 4 — Facebook users (Task 1)",
      after:"The two pie charts compare the age distribution of Facebook users in 2005 and 2015. In 2005, users aged 13–24 made up the largest group at 51%, whereas in 2015 this figure fell to 31%, and users aged 25–40 became the largest group at 47%. Interestingly, in both years people aged 66–80 used Facebook the least. In more detail, in 2005 the age groups accounted for 51% (13–24), 32% (25–40), 16% (41–65) and 1% (66–80). In 2015, the figures were 31%, 47%, 19% and 3% respectively." },
    { title:"Essay 5 — Application letter",
      after:"Dear Sir or Madam, My name is Kaito, and I am writing from Japan. I became curious about your school after seeing its advertisement. I graduated from graduate school in Japan, where I studied IT, so I am able to teach programming and IT. In addition, I have recently been developing a mobile application, which means I am well suited to teaching IT to children who are interested in the field. I look forward to hearing from you. Yours faithfully, Kaito" }
  ]
};
